[package]
name = "graphing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtfs-structures = "0.41.1"
petgraph = "0.6.4"


[[bin]]
name = "gtfs_grapher"
path = "src/gtfs_grapher.rs"
